gin:
  prefix: /intellect
  port: 8094
  mode: debug
  log:
    filters:
      - '/intellect/excel/task'
      - '/intellect/template/finish'
      - '/intellect/images/pdfToJpg/task'
      - '/intellect/images/pdfExtractImg/task'
    client:
      logstash:
        url: 172.17.181.4:5044
      mysql:
        host: 172.17.181.4
        port: 3306
        username: root
        password: qazwsx123!
        database: intellect
gorm:
  mysql:
    host: 172.17.181.4
    port: 3306
    username: root
    password: qazwsx123!
    database: intellect
cache:
  redis:
    host: 172.17.181.4
    port: 6379
    password: qazwsx123!
    database: 5
    maxIdle: 30
    maxActive: 30
    idleTimeout: 200ms
oss:
  minio:
    endpoint: 172.17.180.145
    port: 9000
    accessKey: AKIAIOSFODNN7EXAMPLE
    secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    secure: false
    bucket: oss
    prefix: https://ucc.baidu-int.com/file/show/
mq:
  rocketMq:
    url: http://172.17.181.4:9876
    logLevel: warn
elastic:
  url: http://172.17.181.4:9200
